### ISSUE TITLE
Question regarding the parts which depend on coil impedance

### ISSUE THREAD

**Issue by stmllr** [polykit/kosmo-spring-reverb-driver#1]
Thanks for publishing your gerber files. They work like a charm, a pleasure to solder.

I have some questions about the [parts, which depend on the coil input impedance](https://github.com/polykit/kosmo-spring-reverb-driverREADME.md#coil-impedance).

* Which role do the they play in the schematics? Trying to understand the logic in there.
* Which effects on the sound do you expect when changing their particular values?
* What do you mean with "good result"?

I am currently assembling two PCBs for spring tanks 8BB2C1B and 9BB2C1B, both with 150ohm impedance.
I have successfully finished one and used the values for R5/R13/R19, R10, R6, R7, C2, C3 you proposed in the README.

**Comment by polykit** [comment]
Hi @stmllr, the lower the input coils impedance the higher is the needed current to drive it. This is reflected by the changed resistor values. It is needed to drive the coil at an optimal point and get the best reverberation out of it. I choose this design because it can drive tanks with a high current demand. Also take a look at the references linked in the repository.
